---
title: "210504_tidytuesday_ask_a_manager"
author: "Angela"
date: "5/4/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggResidpanel)
library(ggtext)
library(ggpubr)
```


```{r}
# Read in the data from the tidy tuesday library.
tuesdata <- tidytuesdayR::tt_load(2021, week = 21)
readme(tuesdata)
```

```{r}
# Some basic cleaning of strings
survey <- tuesdata$survey
survey$how_old_are_you <- factor(survey$how_old_are_you, levels = c("under 18", "18-24", "25-34", "35-44", "45-54",
                                                                       "55-64", "65 or over"))

survey <- survey %>%
  mutate(overall_years_of_professional_experience = str_replace_all(overall_years_of_professional_experience, 
                                                                    c("year " = "", " years" = "")),
         years_of_experience_in_field = str_replace_all(years_of_experience_in_field, 
                                                                    c("year " = "", " years" = ""))) %>% 
  mutate(overall_years_of_professional_experience = if_else(overall_years_of_professional_experience %in% 
                                                              c("1 or less", "41 or more"), 
                                                            overall_years_of_professional_experience, 
                                                            str_replace_all(overall_years_of_professional_experience, " ", "")),
         years_of_experience_in_field = if_else(years_of_experience_in_field %in% 
                                                              c("1 or less", "41 or more"), 
                                                            years_of_experience_in_field, 
                                                            str_replace_all(years_of_experience_in_field, " ", "")))

survey$country <- str_to_title(survey$country)
survey$country <- if_else(survey$country %in% c("California", "San Francisco", "The United States", "The Us", "U. S", "U. S.", "U.s",
                                                "U.s.", "U.s.a", "U.s.a.", "U.s>", "U.sa", "Uniited States", "Unite States", 
                                                "United  States", "United Sates", "United Sates Of America", "United Stares", "United State",
                                                "United State Of America", "United Statea", "United Stated", "United Stateds", 
                                                "United Statees", "United States Of America", "United States Of American", 
                                                "United States Of Americas", "United Statesp", "United Statew", "United Statss", 
                                                "United Stattes", "United Statues", "United Status", "United Statws", "United Sttes",
                                                "Unitedstates", "Uniteed States", "Unitef Stated", "Uniter Statez", "Unites States", 
                                                "Unitied States", "Uniyed States", "Uniyes States", "Unted States", "Untied States", 
                                                "Us", "Us Of A", "Usa", "Usaa"), "United States", survey$country)
           
survey$gender[which(survey$gender == "Prefer not to answer")] <- "Other or prefer not to answer"
```                    


```{r}
# Select only the rows that I want to use.

survey_reduced <- survey %>%
  filter(country == "United States", currency == "USD", !is.na(gender),
         !how_old_are_you %in% c("under 18", "65 or over")) %>%
  group_by(race) %>%
  filter(n() >= 500) %>%
  ungroup()

```


```{r}
library(grid)
annotations <- data.frame(label = "Age Group", 
                          how_old_are_you = c("35-44"))

survey_reduced %>%
  ggplot(aes(y = annual_salary, x = race, fill = how_old_are_you)) +
  geom_boxplot(alpha = 0.8, show.legend = FALSE) +
  facet_grid(how_old_are_you~.)  +
#  scale_x_continuous(sec.axis = dup_axis(name = "Bla Bla Bla")) +
  scale_y_continuous(name = "Annual Salary", limits = c(0, 500000), breaks = c(100000, 200000, 300000, 400000, 500000)) +
  scale_fill_brewer(palette = "Paired") +
  coord_flip(clip = "off") +
  theme_pubclean() +
  labs(title = "<b><span style = 'font-size:16pt;face:bold'>Manager Salaries in the US</span></b><br>Data from the Ask a Manager Survey", 
       x = "Race",
       caption = "Data: Gentry et al. (2021) | #TidyTuesday | @Alessine") +)  +
  theme(
    axis.title.y = element_text(),
    axis.title.y.right = element_text())
#  geom_text(data = annotations, 
#            mapping = aes(x = 5, y = 500000, label = label), 
#            hjust   = -0.1, 
#            vjust   = -1,
#            angle = -90)

"Are CEO dismissals getting more common?From 1996 to 2018, there was a downward trend in voluntary departures, while the amount of dismissals remained almost constant. Therefore the likelihood that a departure was involuntary has slightly increased."

```


```{r}
colnames(survey_reduced)

```



```{r}
linmod_1 <- lm(annual_salary ~ how_old_are_you + industry + state + gender + race, data = survey_reduced)

summary(linmod_1)
resid_panel(linmod_1)
```



```{r}
regression_df <- survey %>%
  filter(country == "United States") %>%
  select(c(2, 3, 6, 12:18))

head(regression_df)
```



