---
title: "210420_tidytuesday_netflixshows"
author: "Angela"
date: "4/20/2021"
output: html_document
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(stringr)
library(vioplot)
library(gghalves)
```


```{r}
# Read in the data from the tidy tuesday library.
tuesdata <- tidytuesdayR::tt_load(2021, week = 17)
df_netflix_shows <- data.frame(tuesdata[1])
```


```{r}
df_netflix_movies <- df_netflix_shows %>%
  separate(netflix_titles.country, "first_country", ",") %>%  
  filter(netflix_titles.type == "Movie" & 
           between(netflix_titles.release_year, 2000, 2021) &
           !is.na(first_country))

```


```{r}
df_netflix_movies %>% 
  group_by(netflix_titles.release_year, first_country) %>%
  count(first_country) %>%
  filter(n > 10) %>%
  ggplot(aes(netflix_titles.release_year, n, fill = first_country)) +
  geom_bar(stat = "identity", show.legend = TRUE) +
  theme_light() +
  scale_fill_discrete()
```

```{r}
countries_list <- df_netflix_shows %>% 
  separate(netflix_titles.country, "first_country", ",") %>%
  group_by(first_country) %>%
  count(first_country) %>%
  arrange(desc(n)) %>%
  filter(!is.na(first_country)) %>%
  .$first_country

countries_list[1:10]
```
```{r}
df_netflix_shows %>% 
  separate(netflix_titles.country, "first_country", ",") %>%  
  filter(first_country %in% countries_list[1:10] &
           netflix_titles.type == "Movie") %>%

  ggplot(aes(fct_rev(first_country), netflix_titles.release_year, fill = first_country)) +
  geom_violin(alpha = 0.7, show.legend = FALSE) +
  coord_flip() +
  theme_classic() +
  scale_fill_brewer(palette = "Paired")


```

```{r}
raincloud_plot <- df_netflix_shows %>% 
  separate(netflix_titles.country, "first_country", ",") %>%  
  filter(first_country %in% countries_list[1:5]) %>%
  ggplot(aes(fct_rev(first_country), netflix_titles.release_year, color = netflix_titles.type)) +
  geom_half_violin(aes(fill = netflix_titles.type), side = "r", position = "nudge", scale = "count", width = 2, 
                   alpha = 0.9, show.legend = TRUE) +
  geom_half_point(alpha = 0.9, size = 0.01, position = "nudge", side = "l") +
  coord_flip() +
  theme_dark() +
  theme(legend.position = c(0.8, 1.052), legend.direction = "horizontal", legend.title = element_blank()) +
  labs(title = "Movies and TV Shows on Netflix",
       x = "Country of Production", y = "Year of Release") +
  scale_fill_brewer(palette = "Reds") +
  scale_color_brewer(palette = "Reds")
raincloud_plot

ggsave("raincloud_plot.png", raincloud_plot)

```



```{r, fig.width = 10, fig.height = 5}
vioplot_movies <- df_netflix_shows %>% 
  separate(netflix_titles.country, "first_country", ",") %>%  
  filter(first_country %in% countries_list[1:10] &
           netflix_titles.type == "Movie")

vioplot_shows <- df_netflix_shows %>% 
  separate(netflix_titles.country, "first_country", ",") %>%  
  filter(first_country %in% countries_list[1:10] &
           netflix_titles.type == "TV Show")

vioplot_shows$first_country <- str_replace_all(vioplot_shows$first_country, " ", "\n")

png("split_violin.png", width = 1000, height = 500)
vioplot(netflix_titles.release_year~first_country, data = vioplot_shows, col = "orange", plotCentre = "line", side = "right",
        xlab = "Countries", ylab = "Year", main = "Movies and TV Shows on Netflix")
vioplot(netflix_titles.release_year~first_country, data = vioplot_movies , col = "skyblue", plotCentre = "line", side = "left", add = T)
legend("bottomleft", fill = c("skyblue", "orange"), legend = c("Movies", "TV Shows"))
dev.off()
```



```{r}
# Look for specific actors

sum(str_detect(df_netflix_shows$netflix_titles.cast, "Shah Rukh Khan"), na.rm = TRUE)
```


