---
title: "210504_tidytuesday_water_sources"
author: "Angela"
date: "5/4/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggResidpanel)
library(ggtext)
library(ggpubr)
```


```{r}
# Read in the data from the tidy tuesday library.
tuesdata <- tidytuesdayR::tt_load(2021, week = 19)
readme(tuesdata)
```



```{r}
water_sources <- tuesdata$water
water_sources
```


```{r}
water_sources_reduced <- water_sources %>%
  filter(!status_id == "u",
         install_year <= 2021,
         !country_name == "Peru")

water_sources_reduced
```


```{r}
functionality_histogram <- water_sources_reduced %>%
  ggplot(aes(install_year, fill = status_id)) +
  geom_histogram(binwidth = 1) +
  theme_light() +
  theme(panel.grid.minor = element_blank()) +
  labs(title = "Number of Functional and Non-Functional Water Sources",
       x = "Year installed", y = NULL, fill = "Functionality") +
  scale_fill_manual(values = c("lightgrey", "skyblue3"), labels = c("No", "Yes")) +
  scale_y_continuous(labels = function(x) format(x, big.mark = "'", scientific = FALSE))

functionality_histogram

ggsave("210405_functionality_histogram.jpg", functionality_histogram)¨
```



