---
title: "210406_TidyTuesday"
author: "Angela"
date: "April 6, 2021"
output: html_document
---

```{r}
library(tidytuesdayR)
library(treemap)
library(tidyverse)
library(RColorBrewer)

```

```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 15)
```

```{r}
df_brazil_loss <- data.frame(tuesdata[3])
df_brazil_loss <- df_brazil_loss %>%
  rename("Year" = brazil_loss.year, 
         "Commercial crops" = brazil_loss.commercial_crops, 
         "Flooding due to dams" = brazil_loss.flooding_due_to_dams, 
         "Natural disturbances" = brazil_loss.natural_disturbances, 
         "Pasture" = brazil_loss.pasture,
         "Selective logging" = brazil_loss.selective_logging,
         "Fire" = brazil_loss.fire,
         "Mining" = brazil_loss.mining,
         "Other infrastructure" = brazil_loss.other_infrastructure,
         "Roads" = brazil_loss.roads,
         "Tree plantations" = brazil_loss.tree_plantations_including_palm,
         "Small scale clearing" = brazil_loss.small_scale_clearing)
head(df_brazil_loss)
```


```{r}
df_brazil_loss_long <- df_brazil_loss %>% 
  select(c(3:14)) %>%
  pivot_longer(!Year, names_to = "Drivers of loss", values_to = "Area in hectars")

df_brazil_loss_long
```
    

```{r}
treemap2_2001 <- df_brazil_loss_long %>%
  filter(Year == 2001) %>% 
  treemap(index = "Drivers of loss",
          vSize = "Area of rainforest lost in Brazil in 2001",
          type = "index",
          palette = "RdGy")

treemap2_2001
```

```{r}
treemap2_2008 <- df_brazil_loss_long %>%
  filter(Year == 2008) %>% 
  treemap(index = "Drivers of loss",
          vSize = "Area of rainforest lost in Brazil in 2008",
          type = "index",
          palette = "RdGy")

treemap2_2008
```

```{r}
treemap2_2013 <- df_brazil_loss_long %>%
  filter(Year == 2013) %>% 
  treemap(index = "Drivers of loss",
          vSize = "Area in hectars",
          type = "index",
          palette = "RdGy",
          title = "Area of rainforest lost in Brazil in 2013")

treemap2_2013
```

```{r}

```



