---
title: "210504_tidytuesday_olympics"
author: "Angela"
date: "28/7/2021"
output: html_document
---

```{r}
library(tidyverse)
library(tidytuesdayR)
library(waffle)
library(extrafont)
library(devtools)
```


```{r}
# Read in the data from the tidy tuesday library.
tuesdata <- tidytuesdayR::tt_load('2021-07-27')
readme(tuesdata)

olympics <- tuesdata$olympics
regions <- tuesdata$regions
```

```{r}
head(olympics)
```


```{r}
top_athletes <- olympics %>%
  filter(medal == "Gold") %>%
  group_by(name) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  filter(n >= 8) %>%
  select(-n)
```



```{r, fig.width = 10}
# Waffle Chart

waffle_chart <- olympics %>%
  filter(name %in% top_athletes$name) %>%
  group_by(name, medal) %>%
  summarize(n = n()) %>%
  mutate(medal = factor(medal, levels = c("Gold", "Silver", "Bronze"))) %>%  
  arrange(medal) %>%
  ggplot(aes(fill = medal, values = n)) +
  geom_waffle(n_rows = 10, color = "white", size = 0.5, flip = TRUE) +
  facet_wrap(name~., ncol = 3, strip.position = "bottom", labeller = labeller(name = label_wrap_gen(width = 40))) +
  coord_equal() +
  scale_fill_manual(name = NULL,
                    values = c("#FFD700", "#C0C0C0", "#CD7F32"),
                    labels = c("Gold", "Silver", "Bronze")) +
  labs(title = "OLYMPIC MEDALS", subtitle = "How many can one person win?", 
      caption = "Data: Kaggle | #TidyTuesday | @Alessine") +
  theme_void() +
  theme(panel.background = element_rect(fill = "white", color = "white"),
        plot.background = element_rect(fill = "white", color = "white"),
        plot.title = element_text(face = "bold", hjust = 0.5, family = "mono", size = 26),
        plot.subtitle = element_text(face = "bold", hjust = 0.5, family = "mono", size = 20),
        plot.caption = element_text(hjust = 0.5, vjust = -10, family = "mono"),
        strip.text = element_text(family = "sans", size = 10),
        legend.position = "none")

waffle_chart

ggsave("waffle_chart.png")
```
```{r}
# Trying to install the icons - not working. Check back here: https://github.com/wch/extrafont/issues/32
install_fa_fonts()
extrafont::font_import()
extrafont::loadfonts(quiet = TRUE)

extrafont::fonttable() %>% 
  as_tibble() #%>% 
  filter(grepl("Awesom", FamilyName)) %>% 
  select(afmfile, FullName, FamilyName, FontName)
```

```{r, fig.width = 10}
# Pictogram

pictogram <- olympics %>%
  filter(name %in% top_athletes$name) %>%
  group_by(name, medal) %>%
  summarize(n = n()) %>%
  mutate(medal = factor(medal, levels = c("Gold", "Silver", "Bronze"))) %>%  
  arrange(medal) %>%
  ggplot(aes(label = medal, values = n, color = medal)) +
  geom_pictogram(n_rows = 10, color = "black", flip = TRUE) +
  facet_wrap(name~., ncol = 3, strip.position = "bottom") +
  coord_equal() +
  scale_color_manual(name = NULL,
                     values = c(
                       Gold = "#FFD700",
                       Silver = "#C0C0C0",
                       Bronze = "#CD7F32"
                     )) +
  scale_label_pictogram(name = NULL,
                        values = c(
                          Gold = "medal",
                          Silver = "medal",
                          Bronze = "medal"
                        )) +
  labs(title = "OLYMPIC MEDALS", subtitle = "How many can one person win?", 
      caption = "Data: Kaggle | #TidyTuesday | @Alessine") +
  theme_void() +
  theme(panel.background = element_rect(fill = "white", color = "white"),
        plot.background = element_rect(fill = "white", color = "white"),
        plot.title = element_text(face = "bold", hjust = 0.5),
        plot.subtitle = element_text(face = "bold", hjust = 0.5),
        plot.caption = element_text(hjust = 0.5, vjust = -10))

pictogram

ggsave("pictogram.png")
```



