---
title: "210504_tidytuesday_great_lakes_fish"
author: "Angela"
date: "8/6/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(plotly)
```


```{r}
# Read in the data from the tidy tuesday library.
tuesdata <- tidytuesdayR::tt_load('2021-06-08')
readme(tuesdata)
```

```{r}
fishing <- tuesdata$fishing
head(fishing)
```


```{r}
# Getting a basic understanding of what the data looks like

fishing %>%
  filter(between(year, 1910, 2010),
      #    species %in% c("Rainbow Smelt", "Lake Whitefish", "Walleye", "Yellow Perch"),
         lake == "Erie"
     
         ) %>%
  group_by(year, species) %>%
  summarize(total = sum(grand_total, na.rm =TRUE)) %>%
  ggplot(aes(x = year, y = total, color = species)) +
  geom_bar(stat = "identity", show.legend = FALSE)
    
  
```


```{r}
# Selecting only the rows that I want to show
sb_fish_data <- fishing %>%
  filter(between(year, 1990, 2010),
         lake == "Erie"
         ) %>%
  group_by(year, species) %>%
  summarize(total = sum(grand_total, na.rm =TRUE)) %>%
  arrange(-total)

sb_fish_data
```



```{r}
# Wrangling the data into the lists that I need for plotly

fish_by_year <- sb_fish_data %>%
  group_by(year) %>%
  summarize(values = sum(total)) %>%
  arrange(-year)

fish_by_species <- sb_fish_data %>%
  group_by(year, species) %>%
  summarize(values = sum(total)) %>%
  filter(values > 0) %>%
  arrange(-year)

fish_labels = c("Lake Erie", fish_by_year$year, fish_by_species$species)
fish_parents = c("", replicate(length(fish_by_year$year), "Lake Erie"), fish_by_species$year)
fish_values = c(sum(fish_by_year$values), fish_by_year$values, fish_by_species$values)
```


```{r}
# Checking if all the lists have the same length
length(fish_labels) 
length(fish_parents)
length(fish_values)
```

```{r}
# Sunburst plot - some of the labels are identical, so I need to add ids.
sb_fish_plot <- plot_ly(
  labels = fish_labels,
  parents = fish_parents,
  values = fish_values,
  type = 'sunburst',
  branchvalues = 'total',
  sort = FALSE
)
  
sb_fish_plot  
```




```{r}
```


```{r}
```


```{r}

```


```{r}
```


```{r}
```




