---
title: "210427_tidytuesday_ceo_departures"
author: "Angela"
date: "4/27/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggResidpanel)
library(ggtext)
library(ggpubr)
```

```{r}
# Read in the data from the tidy tuesday library.
tuesdata <- tidytuesdayR::tt_load(2021, week = 18)
readme(tuesdata)
```


```{r}
ceo_departures <- tuesdata$departures
ceo_departures
```

```{r}
number_dep <- ceo_departures %>%
  filter(!departure_code == 9, 
         !is.na(ceo_dismissal),
         between(fyear, 1996, 2018)) %>%
  group_by(gvkey) %>%
  summarize(coname = coname[1], no_departures = n()) %>%
  arrange(coname)
```


```{r, fig.width = 5, fig.height = 5}
set.seed(10)
num_dep_scatter <- number_dep %>%
  ggplot(aes(no_departures, coname)) +
  geom_point(size = 0.5, position = "jitter", color = "skyblue4") +
  theme_classic() +
  theme(plot.background = element_rect(fill = "lightgrey"),
        plot.title = element_text(size = 14, margin = margin(t = 8, b = 6), 
                                  face = "bold", family = "Times"),
        axis.title.x = element_text(size = 12, family = "Times"), 
        axis.text.x = element_text(size = 10, family = "Times"), 
        axis.title.y = element_text(size = 12, family = "Times"), 
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(), axis.line = element_blank(),
        plot.caption = element_text(color = "white", size = 8, vjust = 5.8, family = "Sans"),
        plot.margin = unit(c(0.2, 0.5, 0.5, 1),"cm")) +
  labs(x = "Number of Departures per Company", y = "Companies", title = "How often did companies replace their CEO?") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

num_dep_scatter

```


```{r}
ceo_departures <- ceo_departures %>%
  mutate(departure_reason = case_when(
    departure_code == 1 ~ "Death",
    departure_code == 2 ~ "Illness",
    departure_code == 3 ~ "Job Performance",
    departure_code == 4 ~ "Legal Concerns",
    departure_code == 5 ~ "Retirement",
    departure_code == 6 ~ "New Opportunity",
    departure_code == 7 ~ "Other",
    departure_code == 8 ~ "Missing",
    departure_code == 9 ~ "Error"
  ))
```

vjust = 5.8,
```{r, fig.width = 5, fig.height = 5}
dep_reasons_bar <- ceo_departures %>%
  filter(!departure_reason %in% c("Error", "Missing") & 
           !is.na(departure_reason) &
           between(fyear, 1996, 2018)) %>%
  mutate(departure_reason = forcats::fct_infreq(departure_reason)) %>%
  ggplot(aes(fct_rev(departure_reason), fill = as.factor(ceo_dismissal))) +
  geom_bar(stat = "count") +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none", 
        plot.background = element_rect(fill = "lightgrey"),
        plot.title = element_text(size = 14, margin = margin(t = 8, b = 6), 
                                  face = "bold", family = "Times"),
        axis.title.x = element_text(size = 12, family = "Times"), 
        axis.text.x = element_text(size = 10, family = "Times"), 
        axis.title.y = element_blank(), 
        axis.text.y = element_text(size = 10, family = "Times"), 
        axis.ticks = element_blank(), axis.line = element_blank(),
        plot.caption = element_text(color = "black", size = 8, hjust = 0, family = "Times"),
        plot.margin = unit(c(0.2, 0.5, 0.5, 0.5),"cm")) +
  labs(y = "Number of Departures", title = "Why did CEOs leave?") +
  scale_color_manual(values = c("skyblue4", "lightpink3")) +
  scale_fill_manual(values = c("skyblue4", "lightpink3"))

dep_reasons_bar
```

```{r}
scatter_lm_plot <- ceo_departures %>%
  filter(!departure_code == 9,
         !is.na(ceo_dismissal),
         between(fyear, 1996, 2018)) %>%
  count(fyear, ceo_dismissal) %>%
  ggplot(aes(fyear, n, color = as.factor(ceo_dismissal))) +
  geom_line(linejoin = "round") +  
  geom_point() +
  geom_smooth(method = "lm", linetype = "dashed") +
  theme_classic() +
  theme(legend.position = c(0.85, 0.89), legend.direction = "vertical", legend.title = element_blank(), 
        legend.text = element_text(size = 10, family = "Times"),
        plot.background = element_rect(fill = "lightgrey"), 
        plot.title = element_textbox_simple(size = 12, margin = margin(t = 8, b = 6), padding = margin(5.5, 5.5, 5.5, 5.5),
                                  family = "Times", fill = "cornsilk"),
        axis.title.x = element_blank(), 
        axis.text.x = element_text(size = 10, family = "Times"), 
        axis.title.y = element_text(size = 12, family = "Times"), 
        axis.text.y = element_text(size = 10, family = "Times"), 
        axis.ticks = element_blank(), axis.line = element_blank(),
        plot.caption = element_text(color = "black", size = 8, margin = margin(t = 8, b = 1), family = "Times"),
        plot.margin = unit(c(0.2, 0.5, 0.3, 0.4),"cm")) +
  labs(y = "Number of Departures", 
       title = "<b><span style = 'font-size:16pt;face:bold'>Are CEO dismissals getting more common?</span></b><br>From 1996 to 2018, there was a downward trend in voluntary departures, while the amount of dismissals remained almost constant. Therefore the likelihood that a departure was involuntary has slightly increased.", 
       caption = "Data: Gentry et al. (2021) | #TidyTuesday | @Alessine") +
  scale_color_manual(values = c("skyblue4", "lightpink3"), labels = c("voluntary / health", "dismissal")) +
  scale_fill_manual(values = c("skyblue4", "lightpink3"), labels = c("voluntary / health", "dismissal"))

scatter_lm_plot
```

```{r}
dep_by_year <- ceo_departures %>%
  filter(!departure_code == 9,
         !is.na(ceo_dismissal),
         between(fyear, 1996, 2018)) %>%
  count(fyear, ceo_dismissal) %>%
  pivot_wider(names_from = ceo_dismissal, values_from = n) %>%
  rename("dismissal" = "1", "other" = "0")

dep_by_year
```

```{r}
bin_model <- glm(cbind(dismissal, other) ~ fyear, family = "binomial", data = dep_by_year)
tidy(bin_model, exponentiate = TRUE)
```

```{r}
resid_panel(bin_model)
```


```{r, fig.width = 10, fig.height = 8}
combined_plots <- ggarrange(scatter_lm_plot, ggarrange(num_dep_scatter, dep_reasons_bar, ncol = 2), nrow = 2, heights = c(1.5, 1))
combined_plots
ggsave("all_plots_combined.jpg", combined_plots)
```


